### ISSUE TITLE
`AccessDenied` error for S3 buckets hosting a website

### ISSUE THREAD

**Issue by mstn** [serverless-components/aws-cloudfront#12]
Hello!

I am using this component in combination with [@serverless/website](https://github.com/serverless-components/website). In particular, I want to use https for an S3 website bucket and Cloudfront seems the best option.

My `serverless.yml` looks like

```
website:
  component: "@serverless/website"
  ...

secureWebsite:
  component: '@serverless/aws-cloudfront'
  inputs:
    ...
    origins:
      - ${website.url}
```
Apparently (see [code](https://github.com/serverless-components/aws-cloudfront/blob/master/lib/getOriginConfig.js#L18)), if `originUrl` is an S3 bucket url, the input url is replaced with `${bucketName}.s3.amazonaws.com`.

In this way, when I try to access the website via cloudfront url I get an `AccessDenied` error. If I replace by hand in AWS the url with the original one `${website.url}` (e.g, `bucket-name-xxx.s3-website.my-region.amazonaws.com`, it works as expected.
