### ISSUE TITLE
Support for Aliases and ViewerCertificate configuration

### ISSUE THREAD

**Issue by mdwt** [serverless-components/aws-cloudfront#14]
I would like to discuss a new feature to be able to specify `Aliases` and `ViewerCertificate` (similar to #13 ) in order to specify multiple CNAME values as well as a certificate ARN that covers all CNAMEs. 

The serverless config can be something like this:

```
# serverless.yml

distribution:
  component: '@serverless/aws-cloudfront'
  inputs:
    region: us-east-1
    ...
    certificateArn: <acmCertArn>
    aliases:
       - <cname1>
       - <cname2>
```

which is then processed in `createCloudFrontDistribution` / `updateCloudFrontDistribution`

 I'll submit the PR if we agree to go ahead.
