### ISSUE TITLE
Make OriginReadTimeout configurable for custom origins

### ISSUE THREAD

**Issue by Harriebo** [serverless-components/aws-cloudfront#28]
We use the custom origins to map the old api while moving to NextJs which contain some old endoints which need a higher timeout, at this moment we cant use the serverless config to set this since its hardcoded to 30.

https://github.com/serverless-components/aws-cloudfront/blob/6f15e0733e27c80ad16723d7c8452657f75d0fd9/lib/getOriginConfig.js#L36

for example:
```yml
    cloudfront:
      origins:
        - url: https://url/
          originReadTimeout: 60
          pathPatterns:
            /old-api/*:
              allowedHttpMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
```
